name: Build Linux32-Intel
on: [workflow_dispatch]

jobs:
  build-linux32:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          repository: felias-fogg/avr-gdb
          ref: linux32

      - name: build
        run: |
          sudo ./avr-gdb-build.sh linux32 intel
          sudo cp ./build/avr-linux32-intel/bin/avr-gdb .
          tar cvz --exclude="*DS_Store" --exclude="*/._*" -f x86-linux.tar.gz avr-gdb
 
      - name: upload
        uses: actions/upload-artifact@v6
        with:
          name: Linux32-bit
          path: x86-linux.tar.gz
      