name: Build Linux32-Intel
on: [workflow_dispatch]

jobs:
  build-linux32:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          architecture: x86

     - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # Install dependencies

      - name: Package PyAvrOCD with PyInstaller
        run: |
          pyinstaller -y pyavrocd.spec

      - name: Run pyavrocd
        run: |
          dist/pyavrocd/pyavrocd -V
          dist/pyavrocd/pyavrocd -d ? -t ?

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: i686-linux-gnu
          path: dist/pyavrocd/*
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
