# Triggered by a new release, will create new binaries
name: Release workflow

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Test release version against system version
        if: ${{ github.event.release.tag_name != '' }}
        run: |
          VER=v$(cat VERSION)
          REL=${{ github.event.release.name }}
          echo "Github release name: $REL"
          echo "AVR-GDB version: $VER"
          if [ "x$VER" != "x$REL" ]; then
             echo "Release version does not match system version"
             exit 1
          fi
          echo "Release and system version are identical, now we continue"

  build-x86_64-apple-darwin:
    needs: check
    runs-on: macos-14-large
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup
        run: |
          echo "OS=macos" >> $GITHUB_ENV
          echo "ARCH=intel" >> $GITHUB_ENV
          echo "PREF=x86_64-apple-darwin" >> $GITHUB_ENV

      - name: patch and build 
        run: |
          ./avr-gdb-build.sh ${{ env.OS }} ${{ env.ARCH }}
          rm -rf tool
          mkdir tool
          mv build/avr-${{ env.OS }}-${{ env.ARCH }}/bin/avr-gdb tool
          mv build/avr-${{ env.OS }}-${{ env.ARCH }}/package.json tool
          tar -cvz --exclude="*DS_Store" --exclude="*/._*" -f ${{ env.PREF }}.tar.gz tool

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREF }}
          path: ${{ env.PREF }}.tar.gz
          overwrite: true
          if-no-files-found: error

  build-arm64-apple-darwin:
    needs: check
    runs-on: macos-14
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup
        run: |
          echo "OS=macos" >> $GITHUB_ENV
          echo "ARCH=arm" >> $GITHUB_ENV
          echo "PREF=arm64-apple-darwin" >> $GITHUB_ENV

      - name: patch and build 
        run: |
          ./avr-gdb-build.sh ${{ env.OS }} ${{ env.ARCH }}
          rm -rf tool
          mkdir tool
          mv build/avr-${{ env.OS }}-${{ env.ARCH }}/bin/avr-gdb tool
          mv build/avr-${{ env.OS }}-${{ env.ARCH }}/package.json tool
          tar -cvz --exclude="*DS_Store" --exclude="*/._*" -f ${{ env.PREF }}.tar.gz tool

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREF }}
          path: ${{ env.PREF }}.tar.gz
          overwrite: true
          if-no-files-found: error

  build-x86_64-linux-gnu:
    needs: check
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup
        run: |
          echo "OS=linux64" >> $GITHUB_ENV
          echo "ARCH=intel" >> $GITHUB_ENV
          echo "PREF=x86_64-linux-gnu" >> $GITHUB_ENV

      - name: patch and build 
        run: |
          sudo ./avr-gdb-build.sh ${{ env.OS }} ${{ env.ARCH }}
          sudo rm -rf tool
          sudo mkdir tool
          sudo mv build/avr-${{ env.OS }}-${{ env.ARCH }}/bin/avr-gdb tool
          sudo mv build/avr-${{ env.OS }}-${{ env.ARCH }}/package.json tool
          tar -cvz --exclude="*DS_Store" --exclude="*/._*" -f ${{ env.PREF }}.tar.gz tool

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREF }}
          path: ${{ env.PREF }}.tar.gz
          overwrite: true
          if-no-files-found: error

  build-i686-linux-gnu:
    needs: check
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup
        run: |
          echo "OS=linux32" >> $GITHUB_ENV
          echo "ARCH=intel" >> $GITHUB_ENV
          echo "PREF=i686-linux-gnu" >> $GITHUB_ENV

      - name: patch and build 
        run: |
          sudo ./avr-gdb-build.sh ${{ env.OS }} ${{ env.ARCH }}
          sudo rm -rf tool
          sudo mkdir tool
          sudo mv build/avr-${{ env.OS }}-${{ env.ARCH }}/bin/avr-gdb tool
          sudo mv build/avr-${{ env.OS }}-${{ env.ARCH }}/package.json tool
          tar -cvz --exclude="*DS_Store" --exclude="*/._*" -f ${{ env.PREF }}.tar.gz tool

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREF }}
          path: ${{ env.PREF }}.tar.gz
          overwrite: true
          if-no-files-found: error

  build-aarch64-linux-gnu:
    needs: check
    runs-on: ubuntu-24.04-arm
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup
        run: |
          echo "OS=linux64" >> $GITHUB_ENV
          echo "ARCH=arm" >> $GITHUB_ENV
          echo "PREF=aarch64-linux-gnu" >> $GITHUB_ENV

      - name: patch and build 
        run: |
          sudo ./avr-gdb-build.sh ${{ env.OS }} ${{ env.ARCH }}
          sudo rm -rf tool
          sudo mkdir tool
          sudo mv build/avr-${{ env.OS }}-${{ env.ARCH }}/bin/avr-gdb tool
          sudo mv build/avr-${{ env.OS }}-${{ env.ARCH }}/package.json tool
          tar -cvz --exclude="*DS_Store" --exclude="*/._*" -f ${{ env.PREF }}.tar.gz tool

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREF }}
          path: ${{ env.PREF }}.tar.gz
          overwrite: true
          if-no-files-found: error

  build-arm-linux-gnueabihf:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup
        run: |
          echo "OS=linux32" >> $GITHUB_ENV
          echo "ARCH=arm" >> $GITHUB_ENV
          echo "PREF=arm-linux-gnueabihf" >> $GITHUB_ENV
      - name: qemu run
        uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          cpu: arm1176
          import_github_env: true
          base_image: raspios_lite:latest
          copy_artifact_path: arm-linux-gnueabihf.tar.gz
          image_additional_mb: 2048
          commands: |
            df -h /
            sudo apt-get update
            sudo ./avr-gdb-build.sh ${OS} ${ARCH}
            sudo rm -rf tool
            sudo mkdir tool
            sudo cp ./build/avr-${OS}-${ARCH}/bin/avr-gdb tool
            sudo cp ./build/avr-${{ env.OS }}-${{ env.ARCH }}/package.json tool
            tar cvz --exclude="*DS_Store" --exclude="*/._*" -f ${PREF}.tar.gz tool
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREF }}
          path: ${{ env.PREF }}.tar.gz
          overwrite: true
          if-no-files-found: error

  build-x86_64-mingw32:
    needs: check
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup
        run: |
          echo "OS=windows64" >> $GITHUB_ENV
          echo "ARCH=intel" >> $GITHUB_ENV
          echo "PREF=x86_64-mingw32" >> $GITHUB_ENV

      - name: patch and build 
        run: |
          sudo ./avr-gdb-build.sh ${{ env.OS }} ${{ env.ARCH }}
          sudo rm -rf tool
          sudo mkdir tool
          sudo mv build/avr-${{ env.OS }}-${{ env.ARCH }}/bin/avr-gdb.exe tool
          sudo mv build/avr-${{ env.OS }}-${{ env.ARCH }}/package.json tool
          tar -cvz --exclude="*DS_Store" --exclude="*/._*" -f ${{ env.PREF }}.tar.gz tool

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREF }}
          path: ${{ env.PREF }}.tar.gz
          overwrite: true
          if-no-files-found: error

  build-i686-mingw32:
    needs: check
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup
        run: |
          echo "OS=windows32" >> $GITHUB_ENV
          echo "ARCH=intel" >> $GITHUB_ENV
          echo "PREF=i686-mingw32" >> $GITHUB_ENV

      - name: patch and build 
        run: |
          sudo ./avr-gdb-build.sh ${{ env.OS }} ${{ env.ARCH }}
          sudo rm -rf tool
          sudo mkdir tool
          sudo mv build/avr-${{ env.OS }}-${{ env.ARCH }}/bin/avr-gdb.exe tool
          sudo mv build/avr-${{ env.OS }}-${{ env.ARCH }}/package.json tool
          tar -cvz --exclude="*DS_Store" --exclude="*/._*" -f ${{ env.PREF }}.tar.gz tool

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREF }}
          path: ${{ env.PREF }}.tar.gz
          overwrite: true
          if-no-files-found: error

  make-release:
    needs:
      - build-x86_64-apple-darwin
      - build-arm64-apple-darwin
      - build-x86_64-linux-gnu
      - build-i686-linux-gnu
      - build-aarch64-linux-gnu
      - build-arm-linux-gnueabihf
      - build-x86_64-mingw32
      - build-i686-mingw32
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Create subdir
        run: |
          rm -rf assets
          mkdir assets

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          path: assets

      - name: List artifacts
        run: ls -la assets/*

      - name: Asset upload
        if: ${{ github.event.release.tag_name != '' }}
        uses: softprops/action-gh-release@v2
        with:
          files: assets/*